### ISSUE TITLE
change how bands are rendered

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/org.caleydo.view.domino#105]
Before - band separations seems to indicate connectivity across blocks
![screen shot 2014-03-13 at 16 45 31-2](https://f.cloud.github.com/assets/1216518/2411841/11d07da8-aacc-11e3-8c11-ed6edb094ce1.png)

After - without band separations the unordered nature of the blocks is emphasized:
![better_group_bands](https://f.cloud.github.com/assets/1216518/2411842/1707126e-aacc-11e3-8be2-87013c1eaa06.jpg)

**Comment by sgratzl** [comment]
I got the idea for the set band (center) but not for the item bands (right to the scatterplot)

what is the criteria whether the bands should connect to the items or not

**Comment by sgratzl** [comment]
related #112
