### ISSUE TITLE
Label placement for combined blocks

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#107]
Group labels should all be aligned along the same (invisible) line.
In this example, gender and number of studio samples should be placed on the same y position as "Countries in Australia".
If this looks weird, we could think of adding lines that connect the actual data block with the label - like we do in Figure annotations.

![screen shot 2014-03-13 at 17 13 09](https://f.cloud.github.com/assets/4129755/2411688/6a330c7e-aaca-11e3-8143-e30d78415460.png)

**Comment by sgratzl** [comment]
@mstreit  please test

**Comment by mstreit** [comment]
![screen shot 2014-03-15 at 19 14 48](https://f.cloud.github.com/assets/4129755/2429143/ba94c2ee-ac6d-11e3-89da-b995bf764931.png)

Very nice, looks much cleaner now!
I am not sure if we should repeat the partition name in front of the group name, e.g., "Content Europe". Just the group name should be enough in most of the cases. The user still has the explicit partition name at the top or bottom oft the block. Other opinions?

**Comment by sgratzl** [comment]
> The user still has the explicit partition name at the top or bottom oft the block. Other opinions?

the idea was that you can see from which block the groups are coming from. e.g. in case of tcga dataset every stratification group is named: 1, 2, 3, 4,...

**Comment by mstreit** [comment]
I know. But it does not make sense for regular dataset where we don't have algorithmically generated stratifications. Maybe, that's something we want to change in the settings.
