### ISSUE TITLE
Item Band Mode should be always lines/points

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#112]
currently only if the band is to small lines and points are used. 

but this should be always the case and connected in "thicker" cases using a small dot, similar to LineUp

**Comment by sgratzl** [comment]
![screen](https://f.cloud.github.com/assets/4129778/2420927/6a81a86a-ab7a-11e3-9627-c1bdf43b8852.png)

**Comment by mstreit** [comment]
Yes, looks less cluttered now.
