### ISSUE TITLE
Label Vertical Alignment

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#113]
LabelElement -> if enough vertical space is available, the item should be centered. Currently they stick to the bottom.

**Comment by sgratzl** [comment]
current state:

![s](https://f.cloud.github.com/assets/4129778/2421176/83c2ec9a-ab7e-11e3-973c-9537a4e33865.png)

@mstreit or do you mean something different?

**Comment by mstreit** [comment]
No, this fixed the bug.
