### ISSUE TITLE
Axis Improvement

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#122]
in axis value marker:

instead of a dot, test:
- a diamond: <>
- a "inverted" diamond: ><

**Comment by sgratzl** [comment]
from left to right: point, rect, diamond, inverted diamond, none

![glyphs](https://f.cloud.github.com/assets/4129778/2438070/c39adb22-aded-11e3-88bf-e2a78e42a0be.png)

**Comment by mstreit** [comment]
In this example, I like the square most. Other opinions?

**Comment by ngehlenborg** [comment]
Square works well and so do the facing triangles. I would go for squares.

**Comment by alexsb** [comment]
Agree.
