### ISSUE TITLE
Allow Block Interleaving

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#128]
meaning: one block / node with multiple associated data.

e.g. country -> #sold albums + #sold singles shown as a stacked bar

how to combine: either mathematical to reduce the dataset to a single one (e.g. a+b, a-b,...) or show both directly (e.g. stacked bar)

goal: showing two numerical values, should encode more than just two independent ones

ways to show both directly: 
- bar plot -> stacked bar
- heatmap?
- histogram?
- box plot?
- axis?

**Comment by ngehlenborg** [comment]
A use case where this is crucial are KM plots. They basically don't work when they are plotted into separate blocks.
