### ISSUE TITLE
Find a better way to change the detail level of bands

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#13]
current: (ctrl)-right-click on a band

**Comment by sgratzl** [comment]
possibility: -> popup menu, similar to the hovered popup menu
- a real context menu

options:
- radio button for selecting the level (just the possible ones)

**Comment by mstreit** [comment]
A first improvement would be to just use Ctrl in a ring fashion (after last mode switch to first)
