### ISSUE TITLE
Change Ruler Visual Representation

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#131]
e.g. similar to 

![adventure-racing-corner-ruler-l](https://f.cloud.github.com/assets/4129778/2474249/b8c181ac-b049-11e3-8ce0-907f60568adf.gif)

**Comment by mstreit** [comment]
Google maps uses a very compact representation. 

![image](https://f.cloud.github.com/assets/4129755/2474335/71049830-b04a-11e3-849b-5c572078dfde.png)

**Comment by mstreit** [comment]
I think its a good idea to combine the label with the number of entities.
"100 artists |___________|"

**Comment by sgratzl** [comment]
possible version:

![ruler2](https://f.cloud.github.com/assets/4129778/2477549/5448647e-b072-11e3-8dcc-6ecfe7c74220.png)

**Comment by mstreit** [comment]
looks good. the orange bar should not be wider than the black border. also white space in between the black lines and the orange blocks could make it look nicer. this way, the selection block would be embedded inside the ruler.

**Comment by alexsb** [comment]
yes - the orange block could even be a line

**Comment by sgratzl** [comment]
> yes - the orange block could even be a line

it can't be a line, since you are able to drag it away and a line would be difficult to pick.

![ruler3](https://f.cloud.github.com/assets/4129778/2477931/db48e6ce-b077-11e3-90f3-db03f79914e4.png)

**Comment by alexsb** [comment]
looks awesome like this
