### ISSUE TITLE
Band Obstacle

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#132]
because all bands are automatically created, the board may gets cluttered. 

I personally use an axis of a different item type to create an artificial obstacle, to remove bands. 

A generic version (e.g. just a line, which can be moved, scaled, ....) would be useful

**Comment by sgratzl** [comment]
![obstacle](https://f.cloud.github.com/assets/4129778/2490662/169b55c4-b1bb-11e3-9b1b-c14abacc8183.png)

**Comment by mstreit** [comment]
great idea! we should also describe it in the paper.
