### ISSUE TITLE
support matrix of matrices

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/org.caleydo.view.domino#138]
Say I have 4 gene x patient matrices and I would like to connect them like this:

```
AB
CD
```

Right now I can only attach D either to C or to B but not to both.

**Comment by sgratzl** [comment]
right know this is on purpose. The problem is that such behavior would result in circles, which I can't handle at the moment. Especially adding such a problem is challenging, since you have to strongly connected to multiple ones at the same time
