### ISSUE TITLE
support creation of I1 x I1 or I2 x I2 correlation matrices based on I1 x I2 matrices

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/org.caleydo.view.domino#142]
This would be a very neat feature.

Correlation measures:
- Spearman
- Pearson
- etc.

**Comment by sgratzl** [comment]
maybe similar to #34, but in this case it will be projected to a correlation matrix. So you can either project the l1 x l2 to l1 x l1 or l2 x l2 matrix block, while the values are computed using Spearman, Pearson,...
