### ISSUE TITLE
Introduce "groups" for adjacent items

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.domino#15]
Related to #1 and #5. I found it frustrating that I can't move two elements (columns) that are stuck together at once. However, maybe the solution discussed in #1 isn't quite what we want: instead we might want a tangible concept of a group. The group could have a pickable area, where I can move the whole group.

I'm also wondering, whether by default we should  pick that group, instead of the individual element and use a specific action for picking an individual element.

**Comment by sgratzl** [comment]
wontfix: #1 multi dragging works quite well
