### ISSUE TITLE
In-place menus vs global menu.

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.domino#16]
Right now the system uses a global menu. Should this be replaced with in-place pop-up menus (which I'd prefer)?

**Comment by sgratzl** [comment]
where to place the popup menu, when the user selects more than one item?. e.g. a block, a range of items....

**Comment by sgratzl** [comment]
current strategy:
- for single nodes: title-bar popup menus
- in addition: global menu
- in addition: context menu

**Comment by sgratzl** [comment]
screenie:

![2014-01-24 11_49_47-greenshot](https://f.cloud.github.com/assets/4129778/1994027/53c41b6e-84e5-11e3-801f-9d0f37375a07.png)
