### ISSUE TITLE
Band Browsing Mode

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#18]
new global state mode for band browsing

features:
- just block selections
- all bands between the selected blocks are shown
- all non relevant bands are hidden
- all non selected blocks are hidden, but the contour should be still visible

**Comment by sgratzl** [comment]
normal view: (intersecting bands are removed)
![normal_nostubs](https://f.cloud.github.com/assets/4129778/1996351/00eadd3c-8513-11e3-93fa-a3f209e2e3b8.png)

band mode: default view (no selection = showing all)
![all_bands](https://f.cloud.github.com/assets/4129778/1996353/010c9aa8-8513-11e3-9955-9fecacffc0fa.png)

band mode: 2 selected
![faded_out](https://f.cloud.github.com/assets/4129778/1996352/010bfd3c-8513-11e3-86d0-22f0c29af5f5.png)

**Comment by alexsb** [comment]
Cool, Figure 1 could be visualization art!
