### ISSUE TITLE
Node/Group/Block labels

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#22]
in the top left corner the currently hovered item will be shown. 

But we need another more direct way to show all the labels.

e.g. just at the linear-blocks borders (top, right) + shifted if not enough space (horizontally)

![sketch](https://f.cloud.github.com/assets/4129778/1985978/204f5554-8446-11e3-8496-31ef02558de6.png)

**Comment by sgratzl** [comment]
current version:

![2014-01-24 11_10_43-caleydo - domino2 cal](https://f.cloud.github.com/assets/4129778/1993745/d0a6d1e0-84df-11e3-97f6-e256578721f8.png)

**Comment by alexsb** [comment]
Cool!
