### ISSUE TITLE
to_discuss: Visualization Type selector

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#30]
In the current version visualization types, which are invalid according to the current proximity mode (attached, detached, free), are not available. 

A different option would be to enable all, but automatically change to the "higher" proximity mode, when needed.

e.g. 1d data:
attached: heatmap
detached/free: axis

-> would mean that their is no explicit distinction between attached and detached mode (placeholders,...), but just implicit via the visualization type. 

open question: is there a case where you want to force e.g. a heatmap to be detached, even though it is not needed?

**Comment by alexsb** [comment]
Maybe we could show these options in the detached placeholders?

**Comment by sgratzl** [comment]
the idea is to remove the distinction between detached/attached placeholder and add just a single one. From the visualization type it will be derived, whether it should be attached or detached.

the to_discuss point is: do we want that?

**Comment by sgratzl** [comment]
pros:
- the user can always select all possible visualization types for some data
- it would remove a corner case, where the left node needs to change its visualization if I add an attached node (just show a node as a histogram and add an attached other node)
- in the current formalism there is no distinction between attached / detached, too

cons:
- we just have two of three visible proximity levels, since the attached/detached are just implicit
