### ISSUE TITLE
to_discuss: Projection from 2D data to 1D data

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#34]
2D data could be converted to 1D data in X and/or Y direction:

numerical: mean, min, max, ... or any other stats
categorical: distribution, most frequent

**Comment by alexsb** [comment]
Hmm, so, for example, you'd show the average of all patients for each gene. Would make sense if we have homogeneous blocks, not sure about other cases.

**Comment by sgratzl** [comment]
this could be generalized to a collapse row/column feature by group.

e.g. 
two categorical attributes: age-range (0-10,10-20,...) and gender
if stratified by age-range you have two entries per group (male,female). These entries could be collapsed to a single one (both sexes). 

in the 2d case, this could transform a 2d dataset into a 1d one, iff only one group exists

**Comment by sgratzl** [comment]
collapsing for a group could be implemented using custom idtypes and the mapping manager. 

e.g. collapse all samples per gender together -> create a new idtype sample_gender, which is a mult-mapping of male->all male samples, ... and within the numerical do the projection.
