### ISSUE TITLE
Zoom Globally

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/org.caleydo.view.domino#48]
in the current version, if you zoom globally all items will be zoomed individually. What means that the space between two blocks shrinks if you zoom-in.

Alternative could be to zoom globally, i.e. the space between the elements zooms, too = the canvas will be scaled not the elements within

**Comment by sgratzl** [comment]
not needed, or should be fixed by #14

**Comment by sgratzl** [comment]
wrong: it should be done but just if you zoom globally. so the position changes accordingly

open question: what is the center of the zoom operation, i.e. auto-shift

**Comment by sgratzl** [comment]
I implemented a first version of this feature -> please test it. Sometimes it behaves strange, but I have no idea what a good way would be

**Comment by mstreit** [comment]
I think it works pretty well in general.
However, things get weird when downscaling elements to a tiny size and upscaling them afterwards. --> not relevant for the paper.
