### ISSUE TITLE
parcoords issues?

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/org.caleydo.view.domino#77]
I am not sure if this is a bug or a feature, but when I select elements in a box and whisker plot that is part of a "parallel coordinates" plot construct, I get weird selections and the lines going through the middle axis (of three) seem to be interrupted (y values different on left and right of the axis).

The range selected in the box and whisker plot also doesn't correspond to the range of selected bands (see 2nd screenshot).

I can provide the data that I used for these plots.

![screen shot 2014-02-15 at 11 17 46 am](https://f.cloud.github.com/assets/1216518/2178372/ebc88210-9665-11e3-873e-549a61e7b729.png)
![screen shot 2014-02-15 at 12 15 10 pm](https://f.cloud.github.com/assets/1216518/2178373/ebcb4bbc-9665-11e3-8af3-677b496d72c5.png)
![screen shot 2014-02-15 at 11 25 51 am](https://f.cloud.github.com/assets/1216518/2178371/ebc19446-9665-11e3-8956-238f8b745374.png)

**Comment by sgratzl** [comment]
in all the cases the reason is the currently implemented auto-merging feature:

which means that "similar" lines will be merged to a single one, when
1. the have the same (abs_diff < 0.01) locations
2. the are after each other (a_end = b_start)

I disabled the second criteria
