### ISSUE TITLE
Improve representation of non mapped bands

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.domino#82]
It's good that we have an explicit representation for non-mapped IDs. However, the current representation needs to be improved:
![image](https://f.cloud.github.com/assets/4129755/2218826/ec89dad0-9a36-11e3-8543-a6855a14efa2.png)

How about connecting the band ends to a single point (with a fixed size, e.g., 4 pixels) and label that point with "unmapped"?

**Comment by sgratzl** [comment]
> single point (with a fixed size, e.g., 4 pixels) and label that point with "unmapped"?

where should this point be, a simple alternative would be a band pointing at the end of the other side.

**Comment by sgratzl** [comment]
![notmapp2d](https://f.cloud.github.com/assets/4129778/2243334/8c59d52c-9d27-11e3-8de9-08098f3f7b25.png)

**Comment by mstreit** [comment]
Much better.
To make them less salient, they could be a little shorter though.
