### ISSUE TITLE
Shift key for horizontal zoom not working on Mac

### ISSUE THREAD

**Issue by mstreit** [Caleydo/org.caleydo.view.domino#83]
Any ideas?

**Comment by mstreit** [comment]
Works using the Mac Book Pro keyboard without a USB keyboard attached. If I connect an external keyboard, it does not even work on the native keyboard anymore.

**Comment by sgratzl** [comment]
is it Caledyo specific or system global problem? e.g. in Gimp the Shift modifier will be used to add something to the current selection

**Comment by mstreit** [comment]
In Gimp the shift key is working (on both internal and external keyboard).
